In [4]:
import numpy as np

sample = list(range(0,10))
print(sample)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [6]:
 sample = np.arange(0,10)
 print(sample)
 sample = np.arange(0, 20, 2)
 print(sample)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [8]:
sample = np.zeros((5,5))
print(sample)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
sample = np.ones((3,5))
print(sample)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
sample = np.linspace(0,50,10)
print(sample)

[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]


In [37]:
sample = np.eye(5)
print(sample)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [35]:
sample = np.random.rand()
print(sample)

0.40104995455491943


In [21]:
sample = np.random.rand(4)
print(sample)

[0.13118183 0.03637071 0.11318386 0.27663048]


In [24]:
sample = np.random.rand(4,4)
print(sample)

[[0.31305964 0.76200466 0.67080018 0.41375719]
 [0.4645156  0.85129444 0.11580031 0.99891224]
 [0.22132184 0.87798773 0.86378924 0.46982713]
 [0.83021208 0.49475116 0.88844515 0.70993855]]


In [31]:
sample = np.random.randint(1,10)
print(sample)

9


In [32]:
sample = np.random.randint(1,10,(5,5))
print(sample)

[[8 4 5 9 5]
 [7 3 3 2 8]
 [9 9 3 5 8]
 [4 9 7 6 9]
 [4 5 9 7 7]]
