### Todo gran proyecto de análisis de datos empueza por esto

In [1]:
import numpy as np
import pandas as pd

#### Vector normal de Python

In [2]:
data = [1,2,3,4,5]
type(data)

list

#### Vector de Numpy
Todo empieza desde el vector de Numpy ya que permite usar todas sus funcionalidades.

In [3]:
#convertimos un escalar de python a vector de numpy
scalar = np.array(25)
#visualizamos la cantidad de dimensiones
print(scalar.ndim)
type(scalar)

0


numpy.ndarray

In [4]:
#convertimos un vector de python a vector de numpy
vector = np.array(data)
#visualizamos la cantidad de dimensiones
print(vector.ndim)
type(vector)

1


numpy.ndarray

In [5]:
#convertimos una matriz de python a vector de numpy
matriz = np.array([data, data])
#visualizamos la cantidad de dimensiones
print(matriz.ndim)
type(matriz)

2


numpy.ndarray

In [6]:
#convertimos un tensor de python a vector de numpy
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
#visualizamos la cantidad de dimensiones
print(tensor.ndim)
type(tensor)

3


numpy.ndarray

#### Agregar o eliminar dimensione

In [7]:
#se define array con 10 dimensiones
sample = np.array(data, ndmin=10)
print(sample)
sample.ndim

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]


10

In [8]:
#se agrega dimension como fila al array existente
sample = np.expand_dims(np.array([1,2,3]), axis=0)
print(sample)
sample.ndim

[[1 2 3]]


2

In [9]:
#eliminar dimensiones en desuso
vector_1 = np.array([1,2,3], ndmin=5)
print(vector_1, vector_1.ndim)
vector_2 = np.squeeze(vector_1)
print(vector_2, vector_2.ndim)

[[[[[1 2 3]]]]] 5
[1 2 3] 1
